---
abstract: 'Simple class to manage a Lighttpd server'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lighttpd-Control
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.32
  MooseX::Types::Path::Class: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
