---
abstract: 'Simple class to manage a Lighttpd server'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Lighttpd-Control
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.32
  MooseX::Types::Path::Class: 0
version: 0.02
